version: "3"

services:
  app:
    build:
      context: ./docker
    volumes:
      - ./laravel-app:/var/www/app
    ports:
      - "5000:80"
    working_dir: /var/www/app
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/app/public
      TZ: "Asia/Tokyo"

  db:
    image: mysql:5.7
    ports:
      - "6000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"

  testdb:
    image: mysql:5.7
    ports:
      - "6001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test_user
      MYSQL_DATABASE: test_database
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: myapp-mailhog
    ports:
      - "8003:1025"
      - "8100:8025"

  redis:
    image: redis:4.0
    ports:
      - "6379:6379"